# Generated by Django 4.0.3 on 2022-04-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_compare_remove_wishlist_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compareproduct',
            old_name='wishlist',
            new_name='compare',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Completed', 'Order Completed'), ('Order Received', 'Order Received'), ('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Processing', 'Order Processing')], max_length=50),
        ),
    ]
