# Generated by Django 4.0.3 on 2022-04-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_order_order_status_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.CharField(max_length=14)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Received', 'Order Received')], max_length=50),
        ),
    ]
