# Generated by Django 4.0.3 on 2022-04-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_quickcontact_alter_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='teams/images/')),
                ('social_media', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('On the way', 'On the way'), ('Order Received', 'Order Received'), ('Order Processing', 'Order Processing')], max_length=50),
        ),
    ]
